[package]
name = "btc-collider-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bech32 = "0.8.1"
bs58 = "0.4.0"
flate2 = "1.0.22"
log = "0.4.14"
num-bigint = { version = "0.4.3", features = ["rand"] }
num-traits = "0.2.14"
num_cpus = "1.13.0"
rand = "0.8.4"
ripemd160 = "0.9.1"
secp256k1 = "0.20.3"
sha2 = "0.9.8"
simplelog = "0.11.0"

[dev-dependencies]
parameterized-macro = "0.3.1"
