[package]
name = "btc-collider-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = "0.20.3"
sha2 = "0.9.8"
ripemd160 = "0.9.1"
bs58 = "0.4.0"
num-bigint = { version = "0.4.3", features = ["rand"] }
num-traits = "0.2.14"
parameterized-macro = "0.3.1"
bech32 = "0.8.1"
flate2 = "1.0.22"
rand = "0.8.4"
log = "0.4.14"
simplelog = "0.11.0"
